### ISSUE TITLE
Dimensionless units

### ISSUE THREAD

**Issue by GertjanBisschop** [eu-parc/unit-vocabulary#5]
The following units are currently set to be released:
- id: '[placeholder]'
  same_unit_as: UNITLESS
- id: '-'
  unique_name: '-'
  name: '-'
  label: '-'
  same_unit_as: UNITLESS

Publishing a 'placeholder' as a unit seems bizarre.

**Comment by dirkdevriendt** [comment]
After careful consideration, I agree!
We do need at least one generic UNITLESS entry, but also probably not with a dash as id/unique_name and by default with an empty string representation (label) ?

There may then still be an issue with interpreting existing data schemas, where apparently strings like '-', '[placeholder]' and empty strings are used to mean the variable in question is "UNITLESS".
We can either drop support for those options or add the "HasAliases" mixin on the Unit class in the LinkML data model and add them as alternatives, so we can adapt the code to still be able to read in the schemas.

The definition could then become something like:

```
- id: unitless
  same_unit_as: https://qudt.org/vocab/unit/UNITLESS
  quantity_kind: Dimensionless
  unique_name: unitless
  name: unitless
  label: ''
  aliases:
  - '-'
  - '[placeholder]'
  - ''
  context_aliases:
  - property_name: label
    context: QUDT
    alias: UNITLESS
  - property_name: label
    context: IOP
    alias: observation
  current_validation_status: validated
```
